### Get all categories
GET http://localhost:3000/v1/categories
X-API-KEY: RAHASIA
Accept: application/json

### Create new category
POST http://localhost:3000/v1/categories
X-API-KEY: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name": ""
}

### Get detail category
GET http://localhost:3000/v1/categories/3
X-API-KEY: RAHASIA
Accept: application/json

### Update category
PUT http://localhost:3000/v1/categories/1
X-API-KEY: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name": "Handphone"
}

### Delete category
DELETE http://localhost:3000/v1/categories/1
X-API-KEY: RAHASIA
Accept: application/json